apiVersion: apps/v1
kind: Deployment
metadata:
  name: waplshop-deployment
spec:
  selector:
    matchLabels:
      app: application-db
  replicas: 3
  template:
    metadata:
      labels:
        app: application-db
    spec:
      containers:
      - name: wapl-shop
        image: stonehye/sample-app
        imagePullPolicy: Never
        ports:
        - name: nodejs-port
          containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: database-service
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: waplshop-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: waplshop-secrets
                key: database
        envFrom:
        - configMapRef:
            name: waplshop-configmap